HoaWebApplication/Pages/Admin/IDPUsers.cshtml.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using HoaCommon.Extensions.UserClaims;
using HoaEntities.Models.OutputModels;
using HoaEntities.Models.UpdateModels;
using HoaWebApplication.Models.PaginationModels;
using HoaWebApplication.Services.IdentityServer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HoaWebApplication.Pages.Admin
{
    public class IDPUsersModel : PageModel
    {
        private IIDPUserService _iIDPUserService;

        //property that will be used for paginating the user data
        public XPaginationHeaderDto XPaginationDto;

        public IEnumerable<IDPUserViewDto> Users { get; set; }

        [BindProperty(SupportsGet = true)]
        public IDPUserUpdateDto UserToEdit { get; set; }

        //page number, page size, filters, and sorts that will be used for pagination
        [BindProperty(SupportsGet = true)]
        public PageParametersDto PageParameters { get; set; }

        //set the access level of the user to either read only or CRUD access
        [BindProperty(SupportsGet = true)]
        [Display(Name = "Read Only Access?")]
        public bool ReadOnlyAccess { get; set; }

        //set the role of the user
        [BindProperty(SupportsGet = true)]
        public string Role { get; set; }

        //set if user can create posts or not
        [BindProperty(SupportsGet = true)]
        [Display(Name = "Post Creation Access?")]
        public bool PostAccess { get; set; }

        public IDPUsersModel(IIDPUserService iIDPUserService)
        {
            _iIDPUserService = iIDPUserService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            if (!User.IsAdministrator())
            {
                return RedirectToPage("/Account/AccessDenied");
            }

            //set page size temporarily
            PageParameters.PageSize = 5;

            (Users, XPaginationDto) = await _iIDPUserService.GetAllUsersAsync(PageParameters.PageNum, PageParameters.PageSize);

            return Page();
        }

        public IActionResult OnGetFetchEditIDPUsersPartial()
        {
            //see startup in AddMvc for how this partial is fetched
            //this was an answer found at https://softdevpractice.com/blog/asp-net-core-mvc-ajax-modals/
            return Partial("_EditIDPUserPartial", this);
        }

        public async Task<IActionResult> OnPostEditIDPUserAsync()
        {
            if (!ModelState.IsValid)
            {
                return Partial("_EditIDPUserPartial", this);
            }

            await _iIDPUserService.UpdateUser(ReadOnlyAccess, Role, PostAccess, UserToEdit.Id);

            return Partial("_EditIDPUserPartial", this);
        }
    }
}

HoaWebApplication/Pages/Partial/_CreateEditBoardMeetingPartial.cshtml
@using HoaWebApplication.Pages.BoardMeeting
@model BoardMeetingsModel

@if (TempData["TooManyRequests"] != null)
{
    <br />
    <div class="alert alert-danger">@TempData["TooManyRequests"]</div>
}
else if (TempData["Error"] != null)
{
    <br />
    <div class="alert alert-danger">@TempData["Error"]</div>
}
else
{
    <form class="vn" asp-page="/BoardMeeting/BoardMeetings" asp-page-handler="@(Model.EditMeeting ? "EditMeeting" : "CreateMeeting")">
        @**Below hidden input field is required because the AJAX post requires something
            to verify if the submission was successful*@
        <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />

        @if (Model.EditMeeting)
        {
            <input type="hidden" asp-for="Id" value="@Model?.boardMeeting.Id" />
        }
        <div class="form-group">
            <label asp-for="MeetingToCreateEdit.Title" class="control-label"></label>
            <input asp-for="MeetingToCreateEdit.Title" value="@(Model.EditMeeting ? Model?.boardMeeting.Title : Model?.MeetingToCreateEdit.Title)"
                   class="form-control" placeholder="Meeting Name" />
            <span asp-validation-for="MeetingToCreateEdit.Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="MeetingToCreateEdit.ScheduledLocation" class="control-label"></label>
            <input asp-for="MeetingToCreateEdit.ScheduledLocation" value="@(Model.EditMeeting ? Model?.boardMeeting.ScheduledLocation : Model?.MeetingToCreateEdit.ScheduledLocation)"
                   class="form-control" placeholder="Meeting Location" />
            <span asp-validation-for="MeetingToCreateEdit.ScheduledLocation" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="MeetingToCreateEdit.Description"></label>
            <textarea asp-for="MeetingToCreateEdit.Description" class="form-control" id="tinymcetextarea"></textarea>
            <input type="hidden" id="text-area-content" value="@(Model.EditMeeting ? Model.boardMeeting.Description : Model?.MeetingToCreateEdit.Description)" />
            <span asp-validation-for="MeetingToCreateEdit.Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="MeetingToCreateEdit.ScheduledTime" class="control-label"></label>
            <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                <input asp-for="MeetingToCreateEdit.ScheduledTime" value="@(Model.EditMeeting ? Model?.boardMeeting.ScheduledTime : DateTime.Now)"
                       class="form-control datetimepicker-input" data-target="#datetimepicker1" />
                <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
            </div>
            <span asp-validation-for="MeetingToCreateEdit.ScheduledTime" class="text-danger"></span>
        </div>
    </form>
}

HoaWebApplication/Pages/Partial/_CreateEditCommentPartial.cshtml
@using HoaWebApplication.Pages.Post.Comment
@model CommentsModel

@if (TempData["TooManyRequests"] != null)
{
    <br />
    <div class="alert alert-danger">@TempData["TooManyRequests"]</div>
}
else if (TempData["Error"] != null)
{
    <br />
    <div class="alert alert-danger">@TempData["Error"]</div>
}
else
{
    <form class="vn" asp-page="/Post/Comment/Comments" asp-page-handler="@(Model.EditComment ? "EditComment" : "CreateComment")">
        @**Below hidden input field is required because the AJAX post requires something
            to verify if the submission was successful*@
        <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />

        @if (Model.EditComment)
        {
            <input type="hidden" asp-for="Id" value="@Model?.CommentForView.Id" />
            <input type="hidden" asp-for="PostId" value="@Model?.PostId" />
        }
        else
        {
            <input type="hidden" asp-for="PostId" value="@Model?.PostId" />
        }

        <div class="form-group">
            <label asp-for="CommentToCreateEdit.Message" class="control-label"></label>
            <textarea asp-for="CommentToCreateEdit.Message" class="form-control" id="tinymcetextarea"></textarea>
            <input type="hidden" id="text-area-content" value="@(Model.EditComment ? Model.CommentForView.Message : Model?.CommentToCreateEdit.Message)" />
            <span asp-validation-for="CommentToCreateEdit.Message" class="text-danger"></span>
        </div>
    </form>
}

HoaWebApplication/Pages/Partial/_CreateEditEventPartial.cshtml
@using HoaWebApplication.Pages.Event
@model EventsModel

@if (TempData["TooManyRequests"] != null)
{
    <br />
    <div class="alert alert-danger">@TempData["TooManyRequests"]</div>
}
else if (TempData["Error"] != null)
{
    <br />
    <div class="alert alert-danger">@TempData["Error"]</div>
}
else
{
    <form class="vn" asp-page="/Event/Events" asp-page-handler="@(Model.EditEvent ? "EditEvent" : "CreateEvent")" enctype="multipart/form-data">
        @**Below hidden input field is required because the AJAX post requires something
            to verify if the submission was successful*@
        <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />

        @if (Model.EditEvent)
        {
            <input type="hidden" asp-for="Id" value="@Model.eventForView.Id" />
        }
        <div class="form-group">
            <label asp-for="EventToCreateEdit.Title" class="control-label"></label>
            <input asp-for="EventToCreateEdit.Title" value="@(Model.EditEvent ? Model.eventForView.Title : Model.EventToCreateEdit.Title)"
                   class="form-control" placeholder="Event Title" />
            <span asp-validation-for="EventToCreateEdit.Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EventToCreateEdit.Message" class="control-label"></label>
            <textarea asp-for="EventToCreateEdit.Message" class="form-control" id="tinymcetextarea"></textarea>
            <input type="hidden" id="text-area-content" value="@(Model.EditEvent ? Model.eventForView.Message : Model.EventToCreateEdit.Message)" />
            <span asp-validation-for="EventToCreateEdit.Message" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EventToCreateEdit.ScheduledTime" class="control-label"></label>
            <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                <input asp-for="EventToCreateEdit.ScheduledTime" value="@(Model.EditEvent ? Model.eventForView.ScheduledTime : DateTime.Now)" class="form-control datetimepicker-input" data-target="#datetimepicker1" />
                <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
            </div>
            <span asp-validation-for="EventToCreateEdit.ScheduledTime" class="text-danger"></span>
        </div>
        <div class="custom-file">
            <input asp-for="ImageUploaded.FileToUpload" type="file" class="custom-file-input" accept=".png,.jpg,.bmp" aria-describedby="helptext" id="customFile" /><br />
            <label class="custom-file-label" for="customFile">Choose file</label>
            <span asp-validation-for="ImageUploaded.FileToUpload" class="text-danger"></span>
            <small id="helptext" class="form-text text-muted">
                File is optional, must be an image, and size must be smaller than 2MB.
            </small>
        </div>
    </form>
}

HoaWebApplication/Pages/Partial/_CreateEditPostPartial.cshtml
@using HoaWebApplication.Pages.Post
@model PostsModel

@if (TempData["TooManyRequests"] != null)
{
    <br />
    <div class="alert alert-danger">@TempData["TooManyRequests"]</div>
}
else if (TempData["Error"] != null)
{
    <br />
    <div class="alert alert-danger">@TempData["Error"]</div>
}
else
{
    <form class="vn" asp-page="/Post/Posts" asp-page-handler="@(Model.EditPost ? "EditPost" : "CreatePost")">
        @**Below hidden input field is required because the AJAX post requires something
            to verify if the submission was successful*@
        <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />

        @if (Model.EditPost)
        {
            <input type="hidden" asp-for="Id" value="@Model.post.Id" />
        }
        <div class="form-group">
            <label asp-for="PostToCreateEdit.Title" class="control-label"></label>
            <input asp-for="PostToCreateEdit.Title" value="@(Model.EditPost ? Model.post.Title : Model.PostToCreateEdit.Title)"
                   class="form-control" placeholder="Post Title" />
            <span asp-validation-for="PostToCreateEdit.Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PostToCreateEdit.Message" class="control-label"></label>
            <textarea asp-for="PostToCreateEdit.Message" class="form-control" id="tinymcetextarea"></textarea>
            <input type="hidden" id="text-area-content" value="@(Model.EditPost ? Model.post.Message : Model.PostToCreateEdit.Message)" />
            <span asp-validation-for="PostToCreateEdit.Message" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PostToCreateEdit.Important" class="control-label"></label>
            <select class="custom-select" asp-for="PostToCreateEdit.Important">
                <option selected=@((Model.EditPost ? Model.post.Important : Model.PostToCreateEdit.Important.GetValueOrDefault()) ? "selected" : null) value="true">Yes</option>
                <option selected=@(!(Model.EditPost ? Model.post.Important : Model.PostToCreateEdit.Important.GetValueOrDefault()) ? "selected" : null) value="false">No</option>
            </select>
            <span asp-validation-for="PostToCreateEdit.Important" class="text-danger"></span>
        </div>
    </form>
}

HoaWebApplication/Pages/Partial/_EditIDPUserPartial.cshtml
@using HoaWebApplication.Pages.Admin
@model IDPUsersModel

<form class="vn" asp-page="/Admin/IDPUsers" asp-page-handler="EditIDPUser">
    @**Below hidden input field is required because the AJAX post requires something
        to verify if the submission was successful*@
    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />

    <input type="hidden" asp-for="UserToEdit.Id" value="@Model.UserToEdit.Id" />
    <div class="form-group">
        <label asp-for="ReadOnlyAccess" class="control-label"></label>
        <select class="custom-select" asp-for="ReadOnlyAccess">
            <option selected=@(Model.ReadOnlyAccess ? "selected" : null) value="true">Yes</option>
            <option selected=@(!Model.ReadOnlyAccess ? "selected" : null) value="false">No</option>
        </select>
        <span asp-validation-for="ReadOnlyAccess" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Role" class="control-label"></label>
        <select class="custom-select" asp-for="Role">
            <option selected=@(Model.Role == "admin" ? "selected" : null) value="admin">Admin</option>
            <option selected=@(Model.Role == "board" ? "selected" : null) value="board">Board</option>
            <option selected=@(Model.Role == "user" ? "selected" : null) value="user">User</option>
        </select>
        <span asp-validation-for="Role" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PostAccess" class="control-label"></label>
        <select class="custom-select" asp-for="PostAccess">
            <option selected=@(Model.PostAccess ? "selected" : null) value="true">Yes</option>
            <option selected=@(!Model.PostAccess ? "selected" : null) value="false">No</option>
        </select>
        <span asp-validation-for="PostAccess" class="text-danger"></span>
    </div>
</form>

HoaWebApplication/Pages/Partial/_SendAdminEmailPartial.cshtml
@using HoaWebApplication.Pages.Contact
@model ContactAdminModel

@if (TempData["Error"] != null)
{
    <br />
    <div class="alert alert-danger">@TempData["Error"]</div>
}
else
{
    <form class="vn" asp-page="/Contact/ContactAdmin" asp-page-handler="AdminEmail">
        @**Below hidden input field is required because the AJAX post requires something
            to verify if the submission was successful*@
        <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
        <div class="contact-board"></div>
        <input type="hidden" asp-for="EmailProperties.Name" value="@(User?.Identity.Name ?? "Unknown User")" />
        <div class="form-group">
            <label asp-for="EmailProperties.Subject" class="control-label"></label>
            <input asp-for="EmailProperties.Subject" class="form-control" placeholder="Email Subject" />
            <span asp-validation-for="EmailProperties.Subject" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EmailProperties.Message" class="control-label"></label>
            <textarea asp-for="EmailProperties.Message" class="form-control" id="tinymcetextarea"></textarea>
            <input type="hidden" id="text-area-content" />
            <span asp-validation-for="EmailProperties.Message" class="text-danger"></span>
        </div>
    </form>
}

HoaWebApplication/Pages/Partial/_SendBoardEmailPartial.cshtml
@using HoaWebApplication.Pages.Contact
@model ContactBoardModel

@if (TempData["Error"] != null)
{
    <br />
    <div class="alert alert-danger">@TempData["Error"]</div>
}
else
{
    <form class="vn" asp-page="/Contact/ContactBoard" asp-page-handler="BoardEmail" enctype="multipart/form-data">
        @**Below hidden input field is required because the AJAX post requires something
            to verify if the submission was successful*@
        <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
        <div class="contact-board"></div>
        <input type="hidden" asp-for="EmailProperties.Name" value="@User.Identity.Name" />
        <div class="form-group">
            <label asp-for="EmailProperties.Subject" class="control-label"></label>
            <input asp-for="EmailProperties.Subject" class="form-control" placeholder="Email Subject" />
            <span asp-validation-for="EmailProperties.Subject" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EmailProperties.Message" class="control-label"></label>
            <textarea asp-for="EmailProperties.Message" class="form-control" id="tinymcetextarea"></textarea>
            <input type="hidden" id="text-area-content" />
            <span asp-validation-for="EmailProperties.Message" class="text-danger"></span>
        </div>
        <div class="custom-file">
            <input asp-for="EmailProperties.Attachment" type="file" class="custom-file-input" accept=".doc,.docx,.txt,.pdf" aria-describedby="helptext" id="customFile" /><br />
            <label class="custom-file-label" for="customFile">Choose file</label>
            <span asp-validation-for="EmailProperties.Attachment" class="text-danger"></span>
            <small id="helptext" class="form-text text-muted">
                File is optional and must be a word, pdf, or text document. File size must be smaller than 5MB.
            </small>
        </div>
    </form>
}

HoaWebApplication/Pages/Partial/_UploadMeetingMinutePartial.cshtml
@using HoaWebApplication.Pages.BoardMeeting
@model BoardMeetingsModel

@if (TempData["TooManyRequests"] != null)
{
    <br />
    <div class="alert alert-danger">@TempData["TooManyRequests"]</div>
}
else if (TempData["Error"] != null)
{
    <br />
    <div class="alert alert-danger">@TempData["Error"]</div>
}
else
{
    <form class="vn" asp-page="/BoardMeeting/BoardMeetings" asp-page-handler="UploadMeetingMinute" enctype="multipart/form-data">
        <p class="alert alert-info">Uploading a new file will replace the old one</p>
        @**Below hidden input field is required because the AJAX post requires something
            to verify if the submission was successful*@
        <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
        <input type="hidden" asp-for="Id" value="@Model.Id" />
        <div class="custom-file">
            <input asp-for="FileUploaded.FileToUpload" type="file" class="custom-file-input" accept=".doc,.docx,.txt,.pdf" aria-describedby="helptext" id="customFile" /><br />
            <label class="custom-file-label" for="customFile">Choose file</label>
            <span asp-validation-for="FileUploaded.FileToUpload" class="text-danger"></span>
            <small id="helptext" class="form-text text-muted">
                File must be a word, pdf, or text document. File size must be smaller than 5MB.
            </small>
        </div>
    </form>
}